name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexpattern:
    path: ../

  cupertino_icons: ^1.0.6
  string_validator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  statescope: ^2.0.1
  url_launcher: ^6.3.0
  nostr_core_dart: ^1.0.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
