name: hexpattern
description: "Nostr Public Key Color"
version: 9.0.1
repository: https://github.com/1l0/hexpattern

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  benchmark_harness: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
