name: hexpattern
description: "Nostr pubkey to waveform"
version: 2.0.0
repository: https://github.com/1l0/hexpattern

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
